contact_links:
  - name: Tina.io Website Issues ğŸ“–
    url: https://github.com/tinacms/tinacms.org/issues/new
    about: If you're reporting on Tina.io's website, blog, or documentation please visit the tina.io repository.
  - name: Feature Request ğŸ’¡
    url: https://github.com/tinacms/tinacms/discussions/new
    about: Suggest a new idea for the project.
  - name: Questions & Discussion â“
    url: https://discord.com/invite/zumN63Ybpf
    about: Looking for realtime help on using TinaCMS? Join our Discord community!
