contact_links:
  - name: Tina.io Website Issues ğŸ“–
    url: https://github.com/tinacms/tinacms.org/issues/new
    about: If you're reporting on Tina.io's website, blog, or documentation please visit the tina.io repository.
  - name: Feature Request ğŸ’¡
    url: https://github.com/tinacms/tinacms/discussions/new
    about: Suggest a new idea for the project.
  - name: Questions â“
    url: https://community.tinacms.org/
    about: Looking for advice on how to use TinaCMS? Ask a question on our forum!
