name: e2e Tests
on: [push]
jobs:
  cypress-run-ubuntu:
    runs-on: ubuntu-20.04
    # There is currently a bug on chrome 100 that adds an extra space in the editor
    # container: cypress/browsers:node14.17.6-chrome100-ff98
    # container: cypress/browsers:node14.17.0-chrome88-ff89
    container: cypress/browsers:node16.5.0-chrome94-ff93
    name: Cypress E2E on Tests
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.0
          run_install: true
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          browser: ${{ matrix.browser }}
          env: NEXT_PUBLIC_USE_LOCAL_CLIENT=1
          build: pnpm build:e2e
          command: pnpm test:e2e
          start: pnpm start:e2e
          wait-on: 'http://localhost:3000'
          # wait for 3 minutes for the server to respond
          wait-on-timeout: 180
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

  playwright:
    name: 'Playwright E2E on Tests'
    runs-on: ubuntu-20.04
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.0
          run_install: true
      - name: Build tinacms package
        run: |
          cd playwright/tina-playwright
          pnpm build
      - name: Start Playwright example project
        run: |
          cd playwright/tina-playwright
          pnpm run dev &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000
      - name: Run playwright test
        run: |
          cd playwright/tina-playwright
          npx playwright test
